# 工作流名称
name: Sync Image to Aliyun  Example
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: skai24@qq.com
        password: SKai24%@$^*%
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/mysql  docker://registry.cn-hangzhou.aliyuncs.com/skai24/mysql 
         skopeo copy docker://docker.io/mysql:8.0.37 docker://registry.cn-hangzhou.aliyuncs.com/skai24/mysql:8.0.37
         skopeo copy docker://docker.io/mysql:5.7.44 docker://registry.cn-hangzhou.aliyuncs.com/skai24/mysql:5.7.44
     
      
      
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
